version: '3.8'

services:
  backend:
    build: ./hritikmania-backend
    container_name: hritik-backend
    ports:
      - "8000:8000"
    volumes:
      - ./hritikmania-backend:/app
    depends_on:
      - db
    env_file:
      - .env
  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./hritikmania-frontend/build:/usr/share/nginx/html
    depends_on:
      - backend

  frontend:
    build:
      context: ./hritikmania-frontend
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    container_name: hritik-frontend
    ports:
      - "3000:80"

  db:
    image: postgres
    container_name: postgres-hritikmania
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres_data:
