# Generated by Django 5.2.1 on 2025-06-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='movie_posters/')),
                ('director', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('starring', models.TextField()),
                ('release_date', models.DateField()),
                ('box_office_collection', models.CharField(max_length=50)),
                ('source_file', models.FileField(default='not available', upload_to='movie_sources/')),
            ],
        ),
    ]
