# Generated by Django 5.2.1 on 2025-06-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='movie_sources/'),
        ),
    ]
