FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app/

#for local test
#CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"] 

#Run migrations, import movies, then start Gunicorn
CMD bash -c "\
    python manage.py migrate && \
    python manage.py import_movies && \
    gunicorn hritikmania-backend.wsgi:application --bind 0.0.0.0:8000"