apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: hritikmania
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: hritikmenia-backend-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: hritikmenia-backend-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hritikmenia-backend-secrets
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
