name: CI - Build & Push to Docker Hub

on:
  push:
    branches:
      - dev

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Echo after Docker login
        run: echo "Docker login completed...."

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./hritikmania-backend
          push: true
          tags: yogeshpc/hritikmania-backend:latest
      - name: Echo after Backend build
        run: echo "Backend image pushed...."

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./hritikmania-frontend
          push: true
          tags: yogeshpc/hritikmania-frontend:latest
      - name: Echo after Frontend build
        run: echo "Frontend image pushed..."
